[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.matt-nicole-review]

    [context.matt-nicole-review.functions]

      [context.matt-nicole-review.functions.emails]
      included_files = [
        "./emails/**"
      ]
[[redirects]]
  from = "/podcast"
  to = "/podcasts"

[[redirects]]
  from = "/content-content-podcast"
  to = "/podcasts"

[[redirects]]
 from = "*/professional-technical-writing-examples"
 to = "static-site-transformation"