[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

[[redirects]]
  from = "/podcast"
  to = "/podcasts"

[[redirects]]
  from = "/content-content-podcast"
  to = "/podcasts"

[[redirects]]
  from = "*professional-technical-writing-examples"
  to = "/static-site-generator"

[[redirects]]
  from = "*contact-ed-marsh-information-architect-technical-writer"
  to = "/contact"
