@startuml
title "11ty Architecture"
!theme cerulean
autonumber
actor "Ed Marsh" as ed
control "Linux Mint virtual machine" as vm
collections Markdown as md
collections Nunjucks as nj
entity HTML as html
entity headerfile as hf
entity footerfile as ff
entity navbar as nb
entity TailwindCSS as css
entity JavaScript as js
database "SSG\n(Eleventy)" as ssg
participant "Browser" as br

group "Environment setup"
ed ->o vm: Creates development environment using VMWare Workstation and Linux Mint Cinnamon
ed ->o vm: Installs ""Node.js""
ed ->o  vm : Installs and configures Eleventy
ed ->o vm : Installs and configures TailwindCSS
end
group "Content strategy"
ed -> md : Converts Wordpress content to Markdown
ed -> md: Organizes content in folders
ed -> md: Adds frontmatter to Markdown files
end

group "Site structure"
ed -> css : Writes custom CSS styles
ed-> nj : Writes Nunjucks templates
ed -> js : Adds navbar JavaScript (with help from Gemini)
end

group "Site generation process"
md -> html : Nunjucks generates HTML from Markdown using templates ("".njk"")
nj -> js:  Nunjucks includes JavaScript
nj -> html : Styling is added to HTML
hf -> ssg: Header is added
ff -> ssg: Footer is added
end
ssg -> br : Displays site in browser

@enduml