@startuml
title "11ty Architecture - how it //really// happened"
!theme cerulean

actor "Ed Marsh" as ed
control "Linux Mint virtual machine" as vm
collections Markdown as md
collections Nunjucks as nj
entity HTML as html
entity Header as hf
entity Footer as ff
entity Navbar as nb
entity TailwindCSS as css
entity JavaScript as js
database "SSG\n(Eleventy)" as ssg
participant "Browser" as br

group Environment setup

ed ->o vm: Creates development environment using VMWare Workstation and Linux Mint Cinnamon
ed ->o vm: Installs ""Node.js""
ed ->o vm: Installs and configures Hugo
end
group Content strategy

ed --> ed : Tries numerous conversion tools to get Wordpress content into Markdown
ed--> ed : Exports Wordpress content as XML file
ed -> md : Converts Wordpress content to Markdown locally
ed -> md : Conversion cruft cleanup
end
ed --> ed : Tries to understand Hugo site structure
ed -> md: Organizes content in folders based on SSG requirements
ed --> ed: Tries to understand Hugo templating
ed -> md: Adds frontmatter to Markdown files
ed-->o ed : Gives up on Hugo
ed ->  vm : Installs and configures Eleventy

group Content creation
ed -> md : Writes additional Markdown content
ed -> md : Adds more frontmatter to work with Eleventy
end


group Site structure
ed --> ed : Tries to learn bare minumum of Nunjucks
ed -> css : Writes custom CSS styles
ed-> nj : Writes Nunjucks templates
ed -> nj : Breaks Nunjucks templates
ed -> nj : Gets some things to work
ed -> nj : Tries to create navbar using official Eleventy plugin
ed -->o ed : Fails.
ed -> vm : Installs and configures TailwindCSS
ed --> ed: Tries to understand TailwindCSS
ed -> nj : Creates ""navbar.njk"" file
ed --> ed : Google Gemini helps creates menu hover script in JavaScript
ed -> css : Implements more CSS including structure
end

group Site generation process

ssg -> html : Nunjucks generates HTML from Markdown using templates ("".njk"")
ed -> nj : Tries to fix stupid things that are breaking
nb -> ssg: Navbar added
ed -> nj : Tries to fix stupid things that are breaking
nj -> js:  Nunjucks includes JavaScript
ed -> html : Styling classes added to HTML
css -> ssg : CSS added to HTML
ed -> html : Tries to fix stupid things that are breaking
hf -> ssg: Header added
ff -> ssg: Footer added
end

ssg -> br : Displays site in browser

ed --> ed : Creates sequence diagrams to document target state and actual state


@enduml